[package]
name = "after_effects_comfyui"
version = "0.1.0"
edition = "2021"
metadata = { winres = "" }

[lib]
crate-type = ["cdylib"]

[dependencies]
after-effects = { git = "https://github.com/AdrianEddy/after-effects.git", branch = "master" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dependencies.pyo3]
version = "0.25.1"
features = ["auto-initialize"]

[build-dependencies]
pipl = { git = "https://github.com/AdrianEddy/after-effects.git", branch = "master" }